use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    generate_service_tables();

    println!("cargo:rustc-env=ONMAP_GIT_COMMIT={}", git_stdout(&["rev-parse", "HEAD"]).unwrap_or("unknown".to_string()));
    println!("cargo:rustc-env=ONMAP_GIT_DESCRIBE={}", git_stdout(&["describe", "--tags", "--dirty", "--always"]).unwrap_or("unknown".to_string()));
    println!("cargo:rustc-env=ONMAP_GIT_DIRTY={}", git_dirty().unwrap_or("null".to_string()));
    println!("cargo:rustc-env=ONMAP_BUILD_PROFILE={}", env::var("PROFILE").unwrap_or_else(|_| "unknown".to_string()));
}

fn generate_service_tables() {
    const PORT_COUNT: usize = 65_536;

    println!("cargo:rerun-if-changed=src/resolving/port_service_mapping.json");

    let json_path = PathBuf::from("src/resolving/port_service_mapping.json");
    let json = fs::read_to_string(&json_path).unwrap_or_else(|err| panic!("failed to read service map JSON at {}: {}", json_path.display(), err));
    let root: serde_json::Value = serde_json::from_str(&json).expect("failed to parse service map JSON");

    let mut service_names = vec!["unknown".to_string()];
    let mut service_ids_by_name = HashMap::from([("unknown".to_string(), 0u16)]);
    let mut tcp_service_ids = [0u16; PORT_COUNT];
    let mut udp_service_ids = [0u16; PORT_COUNT];

    fill_service_ids(&root, "tcp", &mut tcp_service_ids, &mut service_names, &mut service_ids_by_name);
    fill_service_ids(&root, "udp", &mut udp_service_ids, &mut service_names, &mut service_ids_by_name);

    let mut generated = String::new();
    generated.push_str("// This file is @generated by build.rs from src/resolving/port_service_mapping.json.\n");
    generated.push_str("// Do not edit by hand.\n\n");
    generated.push_str(&format!("pub static SERVICE_NAMES: [&'static str; {}] = [\n", service_names.len()));
    for service_name in &service_names {
        generated.push_str("    ");
        generated.push_str(&serde_json::to_string(service_name).expect("failed to escape service name"));
        generated.push_str(",\n");
    }
    generated.push_str("];\n\n");

    push_service_id_array(&mut generated, "TCP_SERVICE_IDS", &tcp_service_ids);
    generated.push('\n');
    push_service_id_array(&mut generated, "UDP_SERVICE_IDS", &udp_service_ids);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set"));
    let output_path = out_dir.join("services_generated.rs");
    fs::write(&output_path, generated).unwrap_or_else(|err| panic!("failed to write generated service lookup tables to {}: {}", output_path.display(), err));
}

fn fill_service_ids(
    root: &serde_json::Value,
    protocol: &str,
    target: &mut [u16; 65_536],
    service_names: &mut Vec<String>,
    service_ids_by_name: &mut HashMap<String, u16>,
) {
    let ports = root
        .get(protocol)
        .and_then(serde_json::Value::as_object)
        .unwrap_or_else(|| panic!("service map JSON is missing object '{}'", protocol));

    for (port, entry) in ports {
        let port: usize = port.parse().unwrap_or_else(|err| panic!("invalid {} port '{}': {}", protocol, port, err));
        assert!(port <= u16::MAX as usize, "{} port '{}' is outside the u16 range", protocol, port);

        let service_name = entry.get("service").and_then(serde_json::Value::as_str).unwrap_or_else(|| panic!("{} port {} is missing string field 'service'", protocol, port));
        let service_id = service_id(service_name, service_names, service_ids_by_name);
        target[port] = service_id;
    }
}

fn service_id(
    service_name: &str,
    service_names: &mut Vec<String>,
    service_ids_by_name: &mut HashMap<String, u16>,
) -> u16 {
    if let Some(id) = service_ids_by_name.get(service_name) {
        return *id;
    }

    let id = u16::try_from(service_names.len()).unwrap_or_else(|_| panic!("too many distinct service names for u16 IDs: {}", service_names.len()));
    service_names.push(service_name.to_string());
    service_ids_by_name.insert(service_name.to_string(), id);
    id
}

fn push_service_id_array(output: &mut String, name: &str, service_ids: &[u16; 65_536]) {
    output.push_str(&format!("pub static {}: [u16; 65536] = [\n", name));
    for chunk in service_ids.chunks(16) {
        output.push_str("    ");
        for id in chunk {
            output.push_str(&id.to_string());
            output.push_str(", ");
        }
        output.push('\n');
    }
    output.push_str("];\n");
}

fn git_stdout(args: &[&str]) -> Option<String> {
    let output = Command::new("git").args(args).output().ok()?;

    if !output.status.success() {
        return None;
    }

    let value = String::from_utf8(output.stdout).ok()?;
    let value = value.trim();

    if value.is_empty() {
        return None;
    }

    Some(value.to_string())
}

fn git_dirty() -> Option<String> {
    let output = Command::new("git")
        .args(["diff", "--quiet", "--ignore-submodules", "HEAD", "--"])
        .status()
        .ok()?;

    match output.code() {
        Some(0) => Some("false".to_string()),
        Some(1) => Some("true".to_string()),
        _ => None,
    }
}
